### ISSUE TITLE
React-Leaflet is not compatible with Server-Side Rendering

### ISSUE THREAD

**Issue by clhenrick** [stamen/panorama-template#5]
Just noticed this in the React-Leaflet documentation:
https://github.com/PaulLeCam/react-leaflet#technical-considerations

**Comment by ericsoco** [comment]
We can't render leaflet maps on the server anyway. No biggie, esp. for SEO. I'm going to close this, but if I missed something please reopen.

**Comment by sethfitz** [comment]
What does that even mean?

"Server-side rendering" of Leaflet maps should mean "adds a map div and references to Leaflet's JS and CSS", right?

**Comment by clhenrick** [comment]
Yeah I'm confused by this as well @mojodna 

@ericsoco but do we still want to use it then? Will Leaflet break if a page that is using React-Leaflet is rendered server side?

**Comment by ericsoco** [comment]
@clhenrick I don't _believe_ so. But I could be wrong...
Let's cross that bridge when we come to it. If we end up server-rendering and run into a problem with `react-leaflet`, we can address it then. In the meantime, it's a frequent enough dependency (Leaflet) that we should leave it in, IMO.

**Comment by clhenrick** [comment]
@ericsoco cool. One thing I'm uncertain about is how CartoDB.JS can be used with React-Leaflet (need to research it more) and I feel like I may end up using that a quite a bit, but that is a separate issue.
